[[redirects]]
  from = "/playstore/*" 
  to = "https://play.google.com/store/apps/details?id=com.bluteshi.ganddee"
  status = 200

[[redirects]]
  from = "/appstore/*"
  to = "https://apps.apple.com/gb/app/ganddee/id6457107823"
  status = 200

[[redirects]]
  from = "/desktop/*"
  to = "https://www.ganddee.com/broken-app-link"
  status = 200

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
